Repository antlr/antlr4, pull requests merged in 2019-07, with the labels that each got.

#2596 getText performance improvement by making UTF32Converter thread_local instead of local.
  contributors.txt
  runtime/Cpp/runtime/src/support/StringUtils.h
Labels: comp:performance, target:cpp

#2598 Use openjdk instead of oraclejdk
  .gitignore
  .travis.yml
  .travis/before-install-linux-csharp.sh
  runtime-testsuite/pom.xml
Labels: comp:build, type:improvement

#2593 Update getting-started.md
  doc/getting-started.md
Labels: comp:doc

#2571 Add unit tests for org.antlr.v4.misc.CharSupport
  tool-testsuite/test/org/antlr/v4/test/tool/CharSupportTest.java
Labels: comp:testing, type:improvement

#2582 Add unit tests for org.antlr.v4.misc.Utils
  tool-testsuite/test/org/antlr/v4/misc/UtilsTest.java
Labels: comp:testing, type:improvement
