Repository antlr/antlr4, pull requests merged in 2021-01, with the labels that each got.

#3019 Invalid generated code and no rules error if only fragments are used
  tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java
  tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/Cpp/Cpp.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/JavaScript/JavaScript.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/PHP/PHP.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/Python2/Python2.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/Python3/Python3.stg
  tool/resources/org/antlr/v4/tool/templates/codegen/Swift/Swift.stg
  tool/src/org/antlr/v4/semantics/BasicSemanticChecks.java
  tool/src/org/antlr/v4/tool/ErrorType.java
Labels: code-gen

#3039 Potential fix to #3038
  runtime-testsuite/processors/src/org/antlr/v4/test/runtime/CommentHasStringValueProcessor.java
Labels: comp:build, comp:testing

#3054 Fix missed version in C# runtime
  runtime/CSharp/Properties/AssemblyInfo.cs
Labels: comp:build
