Repository antlr/antlr4, pull requests merged in 2021-05, with the labels that each got.

#3170 Add Docker image for transparent calling of ANTLR4 from a command line.
  contributors.txt
  docker/.dockerignore
  docker/Dockerfile
  docker/README.md
Labels: comp:build

#3176 Add `go.mod` to go runtime module
  contributors.txt
  runtime/Go/antlr/go.mod
Labels: comp:build, target:go

#3116 Enable dart non nullable by default (NNBD)
  .appveyor/workflow.yml
  .circleci/config.yml
  .circleci/scripts/install-linux-dart.sh
  .travis/before-install-linux-dart.sh
  contributors.txt
  doc/dart-target.md
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Dart.test.stg
  runtime-testsuite/test/org/antlr/v4/test/runtime/dart/BaseDartTest.java
  runtime/Dart/lib/antlr4.dart
  runtime/Dart/lib/src/atn/src/atn.dart
  runtime/Dart/lib/src/atn/src/atn_config.dart
  runtime/Dart/lib/src/atn/src/atn_config_set.dart
  runtime/Dart/lib/src/atn/src/atn_deserializer.dart
  runtime/Dart/lib/src/atn/src/atn_simulator.dart
  runtime/Dart/lib/src/atn/src/atn_state.dart
  runtime/Dart/lib/src/atn/src/info.dart
  runtime/Dart/lib/src/atn/src/lexer_action_executor.dart
  runtime/Dart/lib/src/atn/src/lexer_atn_simulator.dart
  runtime/Dart/lib/src/atn/src/parser_atn_simulator.dart
  runtime/Dart/lib/src/atn/src/profiling_atn_simulator.dart
  runtime/Dart/lib/src/atn/src/semantic_context.dart
  runtime/Dart/lib/src/atn/src/transition.dart
  runtime/Dart/lib/src/dfa/src/dfa.dart
  runtime/Dart/lib/src/dfa/src/dfa_serializer.dart
  runtime/Dart/lib/src/dfa/src/dfa_state.dart
  runtime/Dart/lib/src/error/src/diagnostic_error_listener.dart
  runtime/Dart/lib/src/error/src/error_listener.dart
  runtime/Dart/lib/src/error/src/error_strategy.dart
  runtime/Dart/lib/src/error/src/errors.dart
  runtime/Dart/lib/src/input_stream.dart
  runtime/Dart/lib/src/interval_set.dart
  runtime/Dart/lib/src/lexer.dart
  runtime/Dart/lib/src/ll1_analyzer.dart
  runtime/Dart/lib/src/misc/multi_map.dart
  runtime/Dart/lib/src/parser.dart
  runtime/Dart/lib/src/parser_interpreter.dart
  runtime/Dart/lib/src/parser_rule_context.dart
  runtime/Dart/lib/src/prediction_context.dart
  runtime/Dart/lib/src/recognizer.dart
  runtime/Dart/lib/src/rule_context.dart
  runtime/Dart/lib/src/runtime_meta_data.dart
  runtime/Dart/lib/src/token.dart
  runtime/Dart/lib/src/token_factory.dart
  runtime/Dart/lib/src/token_source.dart
  runtime/Dart/lib/src/token_stream.dart
  runtime/Dart/lib/src/tree/src/pattern/chunk.dart
  runtime/Dart/lib/src/tree/src/pattern/parse_tree_match.dart
  runtime/Dart/lib/src/tree/src/tree.dart
  runtime/Dart/lib/src/tree/src/trees.dart
  runtime/Dart/lib/src/util/bit_set.dart
  runtime/Dart/lib/src/util/murmur_hash.dart
  runtime/Dart/lib/src/util/utils.dart
  runtime/Dart/lib/src/vocabulary.dart
  runtime/Dart/pubspec.yaml
  tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg
Labels: comp:runtime, target:dart

#3174 Making compatibility with actions and predicates in Go better
  contributors.txt
  tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
Labels: actions, target:go
