Repository antlr/antlr4, pull requests merged in 2022-12, with the labels that each got.

#3847 GitHub Workflows security hardening
  .github/workflows/hosted.yml
Labels: actions, type:improvement, comp:testing

#4029 Extract unit test updates by @ericvergnaud needed for TypeScript
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_1.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_2.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_3.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_4.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LeftRecursion/MultipleAlternativesWithCommonLabel_5.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/Basic.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/LR.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/LRWithLabels.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/RuleGetters_1.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/RuleGetters_2.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/TokenGetters_1.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/Listeners/TokenGetters_2.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParseTrees/TokenAndRuleContextString.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelForClosureContext.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelsOnRuleRefStartOfAlt.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ReservedWordsEscaping.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/CSharp.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Cpp.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Dart.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Java.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/JavaScript.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/PHP.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python2.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Python3.test.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Swift.test.stg
Labels: type:improvement, comp:testing

#4030 Extract FileUtils updates by @ericvergnaud
  runtime-testsuite/test/org/antlr/v4/test/runtime/FileUtils.java
Labels: type:improvement, cross-platform-issue, comp:testing

#4034 Eric file objs update
  tool/src/org/antlr/v4/codegen/model/ListenerFile.java
  tool/src/org/antlr/v4/codegen/model/VisitorFile.java
Labels: actions, type:bug
