Repository antlr/antlr4, pull requests merged in 2022-09, with the labels that each got.

#3848 fix: #2016 Fix Go template list reference, go runtime and got test te…
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/ListLabelsOnRuleRefStartOfAlt.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Go.test.stg
  runtime/Go/antlr/prediction_context.go
  tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
Labels: target:go, type:cleanup

#3855 feat: Add a deprecation message to the existing v1 module
  runtime/Go/antlr/go.mod
Labels: target:go, type:cleanup

#3862 Fixes #3733; update ST4 so it uses proper ANTLR 3
  runtime-testsuite/pom.xml
  tool-testsuite/pom.xml
  tool/pom.xml
Labels: comp:build, type:cleanup

#3806 [Python 3] use build and twine to publish source and wheel
  .gitignore
  doc/releasing-antlr.md
Labels: comp:build, target:python2, target:python3

#3871 fix: Restore missing changes to v4 of go runtime
  runtime/Go/antlr/antlrdoc.go
  runtime/Go/antlr/v4/prediction_context.go
Labels: target:go, type:cleanup

#3878 the scope (parser or lexer) in @parser::header was dropped, so keep t…
  tool/src/org/antlr/v4/codegen/model/ListenerFile.java
  tool/src/org/antlr/v4/codegen/model/OutputFile.java
  tool/src/org/antlr/v4/codegen/model/VisitorFile.java
  tool/src/org/antlr/v4/semantics/SymbolCollector.java
  tool/src/org/antlr/v4/tool/ast/ActionAST.java
Labels: actions, type:cleanup

#3884 Describe using antlr4-tools in getting started documentation
  doc/getting-started.md
Labels: comp:doc

#3740 [Go] Add Iterative tree walker in go
  runtime/Go/antlr/tree.go
Labels: trees-contexts, target:go
