Repository antlr/antlr4, pull requests merged in 2023-06, with the labels that each got.

#4295 Add test with grammar name that starts with u
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/uStartingCharDoesNotCauseIllegalUnicodeEscape.txt
Labels: cross-platform-issue, comp:testing

#4299 Introduce PredictionMode testing (SLL and LL)
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/PredictionMode_LL.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec/PredictionMode_SLL.txt
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.cpp.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.cs.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.dart.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.go.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.js.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.php.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.py.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Test.ts.stg
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/main.swift.stg
  runtime-testsuite/test/org/antlr/v4/test/runtime/CustomDescriptors.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/RunOptions.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeRunner.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeTestDescriptor.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeTestDescriptorParser.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/RuntimeTests.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/TraceATN.java
  runtime-testsuite/test/org/antlr/v4/test/runtime/java/JavaRunner.java
  tool-testsuite/test/org/antlr/v4/test/tool/ToolTestUtils.java
Labels: atn-analysis, comp:testing

#4297 Fixed file paths used in `package.json#exports.types`
  runtime/JavaScript/package.json
Labels: target:typescript
