Repository antlr/antlr4, pull requests merged in 2023-05, with the labels that each got.

#4255 Export generated data structures
  tool/resources/org/antlr/v4/tool/templates/codegen/Go/Go.stg
Labels: target:go

#4256 Change closureCheckingStopState from recursive to iterative
  runtime/Go/antlr/v4/parser_atn_simulator.go
Labels: target:go

#4004 Update base image to add multi-arch support
  docker/Dockerfile
  docker/README.md
Labels: comp:build

#4271 Minor typo
  runtime/Python3/src/antlr4/atn/ATNDeserializer.py
Labels: target:python3

#4283 Update dotnet to the latest version in runtime tests (6 -> 7)
  .github/workflows/hosted.yml
  runtime-testsuite/resources/org/antlr/v4/test/runtime/helpers/Antlr4.Test.csproj.stg
Labels: target:csharp

#4292 fix go-target.md, remove duplicate 'get'
  doc/go-target.md
Labels: comp:doc, target:go

#4279 fix: #4128 - Prevent generating escape sequences when Windows directories start with a
  tool/src/org/antlr/v4/codegen/model/OutputFile.java
Labels: code-gen
